### ISSUE TITLE
Debian 11 ARM Parrallels

### ISSUE THREAD

**Issue by beebop1032** [BytesGuy/arm-base-boxes#3]
Hello,

Can you provide a Debian 11 ARM for parralels ? 

Tell me how to create it in a tutorial and I will create it for you :-) 

I need it and if I can contribute, no worries!

**Comment by BytesGuy** [comment]
I still have a bit left on my trial so I can add this shortly 👍

**Comment by BytesGuy** [comment]
@beebop1032 Currently blocked due to this unfortunately:

https://github.com/hashicorp/packer/issues/11688

Hopefully there will be a workaround soon!

**Comment by beebop1032** [comment]
Thanks for your job @BytesGuy ! Can you provide your process for create the package ?

**Comment by BytesGuy** [comment]
You just need to run the buildbox script in the appropriate directory and it should produce the box. The script is a bit dodgy sometimes though as it makes assumptions - I'm planning on writing a single script that will live at the top level of the repo so you can run "buildbox debian-11 parallels" for example, just don't have the time to do it lol

**Comment by BytesGuy** [comment]
Packer now works as the upstream issues are solved, but it seems there is some problem with Parallels where Debian won't boot 

<img width="752" alt="Screenshot 2022-03-30 at 22 19 36" src="https://user-images.githubusercontent.com/955076/160942672-b608070c-26e5-4cc6-8158-73d2ca2815f3.png">

It seems a similar issue to https://github.com/utmapp/UTM/issues/2682 but unsure if this is related to Parallels or not

**Comment by ronanchilvers** [comment]
@BytesGuy I'm not using your templates but I now have a build working with:

Parallels Desktop 17.1.2-51548
Parallels Virtualisation SDK 17.1.2-51548
Debian netinst ISO 11.2.0
Packer 1.8.0

I'm using the PYTHONPATH environment variable to set the module path for the parallels packer plugin (as described in https://github.com/hashicorp/packer/issues/11688). I'm setting `parallels_tools_flavor` to `lin-arm` in my builder stanza to upload the correct tools ISO (not sure if you're building tools into your images) - this caught me out for a while as I had `lin` which uploads the `amd64` ISO.

I'm not using preseed to update packages - I found this was breaking the reboot during provisioning but not 100% sure if this is still the case (I was using debian 11.1.0 originally). Instead I dist-upgrade via a shell provisioner.

Hope this helps!

**Comment by BytesGuy** [comment]
@ronanchilvers interesting, thanks for the feedback! At the moment I'm still unable to get a valid build going here as it hangs during boot after installing. Would you mind sharing your packer file?

**Comment by BytesGuy** [comment]
Managed to resolve this by switching to Debian 11.3 and updating Parallels to 17.1.2

Box is up: https://app.vagrantup.com/bytesguy/boxes/debian-11-arm64

**Comment by beebop1032** [comment]
Thanks but not working with vagrant. Any ideas ?

<img width="1296" alt="Capture d’écran 2022-04-10 à 11 25 52" src="https://user-images.githubusercontent.com/14363155/162611725-0132b75e-b485-4fef-927d-413372a52506.png">
