### ISSUE TITLE
VirtualBox support

### ISSUE THREAD

**Issue by kenji21** [BytesGuy/arm-base-boxes#7]
As of version 7 of VirtualBox (still in beta), you can run arm boxes (if you download the preview : https://download.virtualbox.org/virtualbox/7.0.0/VirtualBox-7.0.0_BETA4-153978-macOSArm64.dmg)

Then you need to patch some files in the vagrant VirtualBox plugin :

https://blogs.oracle.com/scoter/post/getting-vagrant-23-working-with-oracle-vm-virtualbox-70-beta

With no experience creating vagrant boxes, how can I help creating boxes for "VirtualBox arm" ?

**Comment by kenji21** [comment]
not for anytime soon...
https://forums.virtualbox.org/viewtopic.php?f=8&t=107362&p=525724&hilit=debian+arm#p525733

**Comment by BytesGuy** [comment]
@kenji21 Hi 👋 Yeah it is, as per the release notes, `unsupported work in progress` so until this hits some kind of stability, and vagrant supports it, then it won't be worth investing the time into playing with all the workarounds etc. Thanks for bringing this issue up though, it will be interesting to revisit it later on! For now I will close it out 😄
