### ISSUE TITLE
Freezing On Boot

### ISSUE THREAD

**Issue by gilbertlim** [BytesGuy/arm-base-boxes#8]
Hi @BytesGuy

pc : macbook m1 arm

When booting, the following occurs:

![image](https://user-images.githubusercontent.com/61113923/209912742-c1683b01-cf87-4065-8c20-87d07134a1a9.png)

No keyboard input works.
Is there any way to solve it?

Vagrantfile
```
Vagrant.configure("2") do |config|
  config.vm.box = "bytesguy/ubuntu-server-20.04-arm64"


  config.vm.provider "vmware_fusion" do |v|
      v.gui = true
      v.memory = "2048"
      v.linked_clone = false
  end

end
```

**Comment by BytesGuy** [comment]
@gilbertlim Sorry for the delayed response, what turned out to be the issue in the end?
